services:
    tms_search.indexer.elasticsearch:
        class: Tms\Bundle\SearchBundle\SearchIndexer\ElasticSearchIndexer
        abstract: true

    tms_search.handler:
        class: Tms\Bundle\SearchBundle\Handler\SearchIndexHandler
        arguments: []

    tms_search.event.subscriber.indexer:
        class: Tms\Bundle\SearchBundle\Event\Subscriber\IndexerSubscriber
        arguments: ['@tms_search.handler']
